/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sathish' at '1/10/17 6:43 AM' with Gradle 2.14.1
 *
 * @author Sathish, @date 1/10/17 6:43 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
